micronaut:
  application:
    name: mensageria

rabbitmq:
  host: ${RABBITMQ_HOST:localhost}
  port: ${RABBITMQ_PORT:5672}
  username: ${RABBITMQ_USER:user}
  password: ${RABBITMQ_PASS:pass}

rmq:
  config:
    topics: transactions
    timer: 20s

